### ISSUE TITLE
Add funtion to shorten geo names

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#68]
The geo-dimension have some rather long names like _Germany (until 1990 former territory of the FRG)_ . They are annoing while plotting and can cause problems while subsetting like in #67.

It would be nice to have a function to replace long geo names with short ones.

**Comment by jhuovari** [comment]
I have been thinking about this and I would prefer something more general. The geo dimension is not a only one with rather long and unpractical labels, at least for plots.

We could have some kind of translation functions, from official statictical terms to more general terms, or to other languages. And a collection of dictionaries. And everyone could also have their own dictionaries.

However, at the moment I don't have time to implement this.

**Comment by muuankarski** [comment]
>We could have some kind of translation functions, from official statictical terms to more general terms, or to other languages. And a collection of dictionaries. And everyone could also have their own dictionaries.

One way forward could be to utilize [this script](https://github.com/muuankarski/countrycode.multilang/blob/master/parse_wiki.R) I use to extend [countrycode](https://github.com/vincentarelbundock/countrycode)-package to support translations into multiple language (my ad hoc fork [countrycode.multilang](https://github.com/muuankarski/countrycode.multilang) that I actually use a lot). As there are not agency providing a up-to-date list of country names in various languages, the script goes through all sovereign states, and retrieves the country names in all languages that there are articles in wikipedia on a particular country. Works well for Russian regions or Finnish municipalities, and I think would work ok for different NUTS-levels. Kind of the idea is trust the "wisdom of crowds" as an authoritative source is missing.

I made a pull request to `countrycode` but it never lead to any action as I think the author would have preferred more authoritative source. 

Dont know, we should make a separate package on this..

**Comment by jhuovari** [comment]
Nice!

**Comment by antagomir** [comment]
@jhuovari Ok no problem, let us try to come up with a solution later on. The country name translations alone are not sufficient to solve this. Such dictionaries would be useful also in other applications that I'm working on, not only this package so that could deserve further consideration. Anyway, I think this would be a good way fwd.

@muuankarski Your example indeed might make a handy package with relatively small effort. In particular as the procedure appears rather generic. Properly implemented, it might find interesting use cases.

**Comment by antagomir** [comment]
There's again a chance to give a stab on this as we're planning a new CRAN release soon

**Comment by cjyetman** [comment]
FYI... the [countrycode ](https://github.com/vincentarelbundock/countrycode)package now supports converting to short and long country names in many different languages thanks to including [CLDR data](http://cldr.unicode.org/translation/country-names).

**Comment by jhuovari** [comment]
Thanks @cjyetman for the information. I will look in to that. We could just document the use of countrycode-package.

**Comment by jhuovari** [comment]
The CLDR addition to the countrycode is really nice. You get also translations.
Only problem is that it includes only countries. EU, EU28, etc are not included.

```r
dat <- get_eurostat("nama_10_gdp",
                      filters = list(geo = c("FI", "DE", "UK", "EU28"),
                                    na_item = "B1GQ",
                                    unit = "CLV_I10"))

unique(countrycode(dat$geo, "eurostat", "cldr.short.fi"))

## [1] "Saksa"     NA          "Suomi"     "Britannia"
## Warning message:
## In countrycode(dat$geo, "eurostat", "cldr.short.fi") :
## Some values were not matched unambiguously: EU28

```

**Comment by cjyetman** [comment]
True, `countrycode` does not recognize anything but states/nations, and it's pretty particular about that. However, we also implemented a `custom_match` option that can solve that issue...
```r
unique(countrycode(dat$geo, "eurostat", "cldr.short.fi", 
                   custom_match = c("EU28" = "Eurpean Union")))
```

**Comment by jhuovari** [comment]
Yes, I noticed that, and in most user cases, I think, a `nomatch = NULL` could be the right solution. 

We could actually add to the `label_eurostat()` an option to do the geo-labelling with the countrycode.

**Comment by antagomir** [comment]
This would be very useful indeed

**Comment by jhuovari** [comment]
I have now implemented this in countrycode branch.
There are the countrycode argument to give a destination code and the countrycode_nomatch argument to deside for nomatchs. Default is NULL and there is also "eurostat" option, and NA option.

In addition, I added also custom_dic to have a custom dictionary. It can be used also for other variables than just "geo".

Please test and comment.

**Comment by antagomir** [comment]
Thanks! 

At least the automated CRAN checks (inst/extras/build.cran.sh go through without problem.

Except this one note: "Undocumented arguments in documentation object 'label_eurostat'
‘countrycode’

**Comment by jhuovari** [comment]
Was that with the first version? As I accidentally pushed it only to my own fork. Now the second version is on countrycode branch in rOpenGov. At least I don't get any error with checks.

How about the behavior. Is it too messy, as it combines labelling with eurostat, countrycode and original codes?

**Comment by antagomir** [comment]
I synchronized this with master and devel branch, and run the CRAN checks. All seems to be fine now. I pushed the version back to countrycode branch after updating the version number slightly. 

The functionality seems fine to me for now. We can change later if there is further feedback or needs.

I am leaving this open for now just in case there are further comments.

**Comment by antagomir** [comment]
I synchronized this with master and devel branch, and run the CRAN checks. All seems to be fine now. I pushed the version back to countrycode branch after updating the version number slightly. 

The functionality seems fine to me for now. We can change later if there is further feedback or needs.

Shall we now merge this to devel/master?

I am leaving this open for now just in case there are further comments.

**Comment by antagomir** [comment]
There is still an issue with travis. Installation of countrycode package fails. I tried both CRAN and Github versions for .travis.yml but this does not work. I can continue to debug when time allows. Meanwhile. other attempts to solve this are welcome.

**Comment by muuankarski** [comment]
> How about the behavior. Is it too messy, as it combines labelling with eurostat, countrycode and original codes?

Very useful with CLDR country names.Function is getting a bit complex, though, and perhaps we should either include more example in the vignette or create a separate one for labeling examples. Create this for localized maps: http://rpubs.com/muuankarski/431130. Again very useful for many non-UK user of Eurostat. And very timely when Brexit is happening...

**Comment by antagomir** [comment]
countrycode is still failing with travis. I have not found a solution. The example is nice but perhaps we should consider alternatives, or move this one to a blog post instead?

**Comment by cjyetman** [comment]
Is it possible that [.travis.yml](https://github.com/rOpenGov/eurostat/blob/master/.travis.yml) simply missing the line...

` - Rscript -e 'install.packages("countrycode")'`

is what's causing the build to fail on `countrycode`? Frankly, I don't know much about Travis CI, but I made a fork, added that line to `.travis.yml`, and ran a build, and while the build still fails, it doesn't fail with an error mentioning `countrycode`.

**Comment by antagomir** [comment]
Thanks. Much possible and I will incorporate this. Does not solve issues with the other dependencies ie tmap and sf, however.

**Comment by antagomir** [comment]
Seems to work now..
